final_answer_model_name: "Xiaojian9992024/Qwen2.5-Dyanka-7B-Preview"
router_model_name: "Xiaojian9992024/Qwen2.5-Dyanka-7B-Preview"
planner_model_name: "Xiaojian9992024/Qwen2.5-Dyanka-7B-Preview"
search_agent_model_name: "ehristoforu/coolqwen-3b-it"
email_agent_model_name: "ehristoforu/coolqwen-3b-it"
Orchestration_model_name: "nvidia/Orchestrator-8B"
